### ISSUE TITLE
Doing a compose up

### ISSUE THREAD

**Issue by KristjanLuik** [wunderkraut/alpine-varnish#1]
varnish_1  | Can't open log - retrying for 5 seconds
varnish_1  | Can't open VSM file (Cannot open /var/lib/varnish/05b2b75cee2a/_.vsm: No such file or directory
varnish_1  | )

**Comment by aleksijohansson** [comment]
@KristjanLuik This image has been heavily updated. Could you please test if this is still an issue?

**Comment by james-nesbitt** [comment]
closing out of date issue.
